version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"
    commit-message:
      prefix: ""
      prefix-development: "[ci skip]"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
